### ISSUE TITLE
Argo simulator is broken 🛑

### ISSUE THREAD

**Issue by KevinGomezDev** [Shopify/argo-admin-template#101]
### Description:
Argo Simulator fails at initial load due to broken Apollo code on:
https://cdn.shopify.com/shopifycloud/web/assets/v1/argo-admin-host/index.js?timestamp=1622061027513
it shows the following error:
![Screen Shot 2021-05-26 at 3 33 59 PM](https://user-images.githubusercontent.com/25872784/119727359-cdca5480-be37-11eb-8000-db3a159aafa4.png)

### Steps to reproduce:
Run: `$ shopify create extension --type=PRODUCT_SUBSCRIPTION --name="My subscription extension"`
Run: `cd into My subscription extension`
Run: `npm run server`

### Comments:
* Old projects created with same command also failed with same error.
* I did search on Shopify account argo-admin-host repo to try to propose a pull request for this, but I wasn't able to find it.

**Comment by iainmcampbell** [comment]
Hi Kevin, thanks for reporting this! I've reproduced the issue and we’re working on a fix.

**Comment by KevinGomezDev** [comment]
@vividviolet  If we do that we see this in all of our stores
![Screen Shot 2021-05-27 at 5 59 23 PM](https://user-images.githubusercontent.com/25872784/119907264-83b7a080-bf15-11eb-8649-5c7ed561ec36.png)

**Comment by vividviolet** [comment]
As a workaround, can you try running `npm --port=39351`? I think what's missing is the port param.

**Comment by henrytao-me** [comment]
Heads up: we are working on the fix. We will let you know when it's merged. There is no workaround in the meantime.

**Comment by henrytao-me** [comment]
It's fixed now. Can you try it? @KevinGomezDev

**Comment by eyalkenig** [comment]
working for me :+1: thanks!!

**Comment by KevinGomezDev** [comment]
It works now, thanks!

> It's fixed now. Can you try it? @KevinGomezDev
