### ISSUE TITLE
useToast doesn't work in simulator environment

### ISSUE THREAD

**Issue by rpastorelle** [Shopify/argo-admin-template#60]
[Toast](https://github.com/Shopify/argo-admin-template/blob/master/docs/Utilities/Toast.md) util throws in simulator environment.

<img width="670" alt="Screen Shot 2020-08-24 at 3 15 33 PM" src="https://user-images.githubusercontent.com/746320/91091746-aa5e4900-e61c-11ea-813f-b08af2af380c.png">

Sample code:

```js
import React from 'react';
import {useToast, Button} from '@shopify/argo-admin-react';

function App() {
    const {show: showToast} = useToast();

    return <Button onClick={() => showToast('Toast popped!')} label="Pop toast" />;
}
```

**Comment by vividviolet** [comment]
This was fixed in v0.8.0
